import type {
  Profile,
  Lot,
  Bid,
  Order,
  CounterOffer,
  Notification,
  SellerReview,
  TickerItem,
} from "./types";
import { getCountryFlag } from "./utils";

// ============================================================
// Helper: generate timestamps relative to NOW
// ============================================================
function minutesFromNow(m: number): string {
  return new Date(Date.now() + m * 60 * 1000).toISOString();
}
function minutesAgo(m: number): string {
  return new Date(Date.now() - m * 60 * 1000).toISOString();
}
function daysAgo(d: number): string {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();
}

// ============================================================
// PROFILES
// ============================================================
// Sudan's authorized tea wholesalers — each licensed to import from specific origins
export const sellers: Profile[] = [
  {
    id: "s1",
    role: "seller",
    company_name: "Red Sea Tea Wholesale",
    display_name: "Red Sea Tea Wholesale",
    email: "trade@redseatea.sd",
    phone: "+249912345678",
    country: "SD",
    city: "Port Sudan",
    kyc_status: "verified",
    reputation_score: 4.8,
    total_transactions: 142,
    avatar_url: "",
    created_at: daysAgo(365),
    updated_at: daysAgo(1),
  },
  {
    id: "s2",
    role: "seller",
    company_name: "Khartoum Tea Wholesale Co.",
    display_name: "Khartoum Tea Wholesale",
    email: "sales@khartoumtea.sd",
    phone: "+249923456789",
    country: "SD",
    city: "Khartoum",
    kyc_status: "verified",
    reputation_score: 4.6,
    total_transactions: 89,
    avatar_url: "",
    created_at: daysAgo(300),
    updated_at: daysAgo(2),
  },
  {
    id: "s3",
    role: "seller",
    company_name: "Nile Valley Tea Distributors",
    display_name: "Nile Valley Distributors",
    email: "info@nilevalleytea.sd",
    phone: "+249934567890",
    country: "SD",
    city: "Omdurman",
    kyc_status: "verified",
    reputation_score: 4.9,
    total_transactions: 203,
    avatar_url: "",
    created_at: daysAgo(400),
    updated_at: daysAgo(1),
  },
  {
    id: "s4",
    role: "seller",
    company_name: "Blue Nile Tea House",
    display_name: "Blue Nile Tea House",
    email: "trade@bluenile-tea.sd",
    phone: "+249945678901",
    country: "SD",
    city: "Wad Madani",
    kyc_status: "verified",
    reputation_score: 4.7,
    total_transactions: 67,
    avatar_url: "",
    created_at: daysAgo(200),
    updated_at: daysAgo(3),
  },
  {
    id: "s5",
    role: "seller",
    company_name: "Kassala Premium Tea",
    display_name: "Kassala Premium Tea",
    email: "info@kassalatea.sd",
    phone: "+249956789012",
    country: "SD",
    city: "Kassala",
    kyc_status: "verified",
    reputation_score: 5.0,
    total_transactions: 45,
    avatar_url: "",
    created_at: daysAgo(150),
    updated_at: daysAgo(1),
  },
];

// Sudanese retail tea buyers — tea shops, cafés, wholesalers across Sudan
const sudaneseBuyerSeeds = [
  {
    display_name: "Khartoum Shai House",
    owner: "Ahmed Salih",
    email: "ahmed@khartoumshai.sd",
    city: "Khartoum",
  },
  {
    display_name: "Omdurman Grand Café",
    owner: "Fatima Osman",
    email: "fatima@omdurmangrand.sd",
    city: "Omdurman",
  },
  {
    display_name: "Port Sudan Retail Tea",
    owner: "Mohamed Idris",
    email: "mohamed@portsudantea.sd",
    city: "Port Sudan",
  },
  {
    display_name: "Kassala Market Tea",
    owner: "Aisha Khalid",
    email: "aisha@kassalatea.sd",
    city: "Kassala",
  },
  {
    display_name: "Wad Madani Wholesale",
    owner: "Omar Tahir",
    email: "omar@wadmadaniwhl.sd",
    city: "Wad Madani",
  },
];

export const buyers: Profile[] = sudaneseBuyerSeeds.map((seed, i) => ({
  id: `b${i + 1}`,
  role: "buyer" as const,
  display_name: seed.display_name,
  company_name: seed.display_name,
  email: seed.email,
  country: "SD",
  city: seed.city,
  kyc_status: "verified" as const,
  reputation_score: 0,
  total_transactions: 8 + i * 3,
  created_at: daysAgo(100 + i * 20),
  updated_at: daysAgo(i),
}));

export const adminUser: Profile = {
  id: "admin1",
  role: "admin",
  display_name: "Admin",
  email: "admin@shaiblock.com",
  kyc_status: "verified",
  reputation_score: 0,
  total_transactions: 0,
  created_at: daysAgo(500),
  updated_at: daysAgo(0),
};

export const allProfiles = [...sellers, ...buyers, adminUser];

// ============================================================
// LOTS — 12 active lots with varied states
// ============================================================
export const lots: Lot[] = [
  {
    id: "lot1",
    seller_id: "s1",
    lot_number: "SB-2026-00142",
    title: "Kericho Gold GFBOP - March 2026",
    description:
      "Premium golden tips from the Kipkelion estate at 2,100m elevation. Bright amber liquor with muscatel character and a smooth finish.",
    origin_country: "KE",
    origin_region: "Kericho",
    estate_name: "Kipkelion Estate",
    tea_type: "black",
    grade: "GFBOP",
    harvest_date: "2026-03-10",
    harvest_season: "first_flush",
    processing_method: "orthodox",
    elevation_meters: 2100,
    certifications: ["Organic", "Rainforest Alliance"],
    cupping: {
      aroma: 8.5,
      body: 7.5,
      color: 8.0,
      briskness: 7.0,
      flavor: 8.5,
      finish: 8.0,
      overall: 8.0,
    },
    cupping_notes:
      "Bright amber liquor with muscatel character. Floral top notes with a honey-like sweetness. Clean, brisk finish with no astringency.",
    cupped_by: "James Mwangi",
    cupping_date: "2026-03-15",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 50,
    min_purchase_kg: 1,
    reserve_price_per_kg: 5.0,
    starting_price_per_kg: 3.5,
    buy_now_price_per_kg: 7.0,
    bid_increment: 0.1,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(22),
    auction_end: minutesFromNow(23),
    auto_extend_minutes: 3,
    status: "active",
    sample_available: true,
    sample_price: 3.5,
    ships_from_country: "KE",
    ships_from_city: "Kericho",
    estimated_ship_days: 7,
    view_count: 87,
    bid_count: 7,
    watch_count: 12,
    created_at: daysAgo(2),
    updated_at: minutesAgo(3),
    seller: sellers[0],
    current_high_bid: 4.8,
  },
  {
    id: "lot2",
    seller_id: "s2",
    lot_number: "SB-2026-00143",
    title: "Darjeeling FTGFOP1 - First Flush 2026",
    description:
      "Classic Darjeeling first flush from the Makaibari estate. Light, floral, with distinctive muscatel grape notes.",
    origin_country: "IN",
    origin_region: "Darjeeling",
    estate_name: "Makaibari Estate",
    tea_type: "black",
    grade: "FTGFOP1",
    harvest_date: "2026-03-05",
    harvest_season: "first_flush",
    processing_method: "orthodox",
    elevation_meters: 1500,
    certifications: ["Organic", "Fair Trade", "Demeter (Biodynamic)"],
    cupping: {
      aroma: 9.0,
      body: 6.5,
      color: 7.5,
      briskness: 8.0,
      flavor: 9.0,
      finish: 8.5,
      overall: 8.5,
    },
    cupping_notes:
      "Exquisite muscatel grape character with floral high notes. Light copper liquor. Remarkably clean aftertaste.",
    cupped_by: "Khalid Abdallah (Khartoum re-cupping)",
    cupping_date: "2026-03-20",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 25,
    min_purchase_kg: 1,
    reserve_price_per_kg: 12.0,
    starting_price_per_kg: 8.0,
    buy_now_price_per_kg: 15.0,
    bid_increment: 0.5,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(30),
    auction_end: minutesFromNow(15),
    auto_extend_minutes: 3,
    status: "active",
    sample_available: true,
    sample_price: 5.0,
    ships_from_country: "IN",
    ships_from_city: "Darjeeling",
    estimated_ship_days: 10,
    view_count: 124,
    bid_count: 12,
    watch_count: 23,
    created_at: daysAgo(3),
    updated_at: minutesAgo(2),
    seller: sellers[1],
    current_high_bid: 11.5,
  },
  {
    id: "lot3",
    seller_id: "s3",
    lot_number: "SB-2026-00144",
    title: "Ceylon Silver Tips - Premium White",
    description:
      "Ultra-premium silver tips from Nuwara Eliya's highest elevation gardens. Subtle, sweet, and extraordinarily smooth.",
    origin_country: "LK",
    origin_region: "Nuwara Eliya",
    estate_name: "Pedro Estate",
    tea_type: "white",
    grade: "Silver Needle",
    harvest_date: "2026-02-20",
    harvest_season: "first_flush",
    processing_method: "hand_rolled",
    elevation_meters: 1800,
    certifications: ["Organic"],
    cupping: {
      aroma: 9.5,
      body: 5.0,
      color: 9.0,
      briskness: 4.0,
      flavor: 9.0,
      finish: 9.5,
      overall: 9.0,
    },
    cupping_notes:
      "Extraordinarily delicate. Pale gold liquor with notes of honeydew melon and white flowers. Silky mouthfeel.",
    cupped_by: "Priya Wickramasinghe",
    cupping_date: "2026-03-01",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 10,
    min_purchase_kg: 1,
    reserve_price_per_kg: 25.0,
    starting_price_per_kg: 18.0,
    buy_now_price_per_kg: 32.0,
    bid_increment: 1.0,
    currency: "USD",
    auction_duration_minutes: 60,
    auction_start: minutesAgo(15),
    auction_end: minutesFromNow(45),
    auto_extend_minutes: 3,
    status: "active",
    sample_available: true,
    sample_price: 8.0,
    ships_from_country: "LK",
    ships_from_city: "Nuwara Eliya",
    estimated_ship_days: 8,
    view_count: 201,
    bid_count: 5,
    watch_count: 34,
    created_at: daysAgo(1),
    updated_at: minutesAgo(5),
    seller: sellers[2],
    current_high_bid: 23.0,
  },
  {
    id: "lot4",
    seller_id: "s4",
    lot_number: "SB-2026-00145",
    title: "Yunnan Ancient Pu-erh Cake 2020",
    description:
      "Six-year aged raw pu-erh from 300-year-old tea trees in Yunnan's Bulang Mountain region.",
    origin_country: "CN",
    origin_region: "Xishuangbanna",
    estate_name: "Bulang Mountain",
    tea_type: "pu_erh",
    grade: "Gushu",
    harvest_date: "2020-04-01",
    harvest_season: "first_flush",
    processing_method: "hand_rolled",
    elevation_meters: 1700,
    certifications: [],
    cupping: {
      aroma: 8.0,
      body: 9.0,
      color: 7.5,
      briskness: 6.0,
      flavor: 8.5,
      finish: 9.0,
      overall: 8.5,
    },
    cupping_notes:
      "Deep, complex aged character. Notes of wet earth, dried fruit, and camphor. Thick, oily mouthfeel with a long, sweet hui gan.",
    cupped_by: "Li Wei Chen",
    cupping_date: "2026-03-20",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 15,
    min_purchase_kg: 1,
    reserve_price_per_kg: 35.0,
    starting_price_per_kg: 20.0,
    bid_increment: 1.0,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(40),
    auction_end: minutesFromNow(5),
    auto_extend_minutes: 3,
    status: "active",
    sample_available: false,
    ships_from_country: "CN",
    ships_from_city: "Kunming",
    estimated_ship_days: 12,
    view_count: 156,
    bid_count: 9,
    watch_count: 28,
    created_at: daysAgo(2),
    updated_at: minutesAgo(1),
    seller: sellers[3],
    current_high_bid: 33.0,
  },
  {
    id: "lot5",
    seller_id: "s5",
    lot_number: "SB-2026-00146",
    title: "Rwanda Highlands Orthodox Black - March 2026",
    description:
      "Hand-rolled OP1 orthodox black from Nyungwe Highlands — full-bodied, malty, and brisk. The replacement supply Sudanese wholesalers are now sourcing since the Kenya route froze in 2024.",
    origin_country: "RW",
    origin_region: "Nyungwe Highlands",
    estate_name: "Nyungwe Tea Cooperative",
    tea_type: "black",
    grade: "OP1",
    harvest_date: "2026-03-15",
    harvest_season: "rain",
    processing_method: "orthodox",
    elevation_meters: 2400,
    certifications: ["Rainforest Alliance", "UTZ Certified"],
    cupping: {
      aroma: 8.5,
      body: 9.2,
      color: 8.8,
      briskness: 9.0,
      flavor: 8.8,
      finish: 8.5,
      overall: 8.8,
    },
    cupping_notes:
      "Bright copper liquor. Full malty body with stone-fruit notes and a brisk, clean finish. Classic orthodox character — holds up beautifully to milk, sugar, mint, or cardamom.",
    cupped_by: "Marie Uwase",
    cupping_date: "2026-03-18",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 5,
    min_purchase_kg: 1,
    reserve_price_per_kg: 45.0,
    starting_price_per_kg: 30.0,
    buy_now_price_per_kg: 55.0,
    // lot5 is the demo lot: increment is small enough that 20s of
    // aggressive sim bidding can't climb past the $45 reserve on its
    // own, guaranteeing the pending_review phase fires in the video.
    bid_increment: 0.5,
    currency: "USD",
    auction_duration_minutes: 30,
    auction_start: minutesAgo(5),
    auction_end: minutesFromNow(25),
    auto_extend_minutes: 3,
    status: "active",
    sample_available: true,
    sample_price: 12.0,
    ships_from_country: "RW",
    ships_from_city: "Kigali",
    estimated_ship_days: 7,
    view_count: 178,
    bid_count: 4,
    watch_count: 41,
    created_at: daysAgo(1),
    updated_at: minutesAgo(8),
    seller: sellers[4],
    current_high_bid: 32.0,
  },
  {
    id: "lot6",
    seller_id: "s1",
    lot_number: "SB-2026-00147",
    title: "Kenya CTC PF1 - Bulk Grade",
    description:
      "Strong, brisk CTC tea ideal for blending. Consistent quality from the Kipkelion factory.",
    origin_country: "KE",
    origin_region: "Kericho",
    estate_name: "Kipkelion Estate",
    tea_type: "black",
    grade: "CTC PF1",
    harvest_date: "2026-03-01",
    harvest_season: "rain",
    processing_method: "CTC",
    elevation_meters: 2100,
    certifications: ["Rainforest Alliance"],
    cupping: {
      aroma: 6.5,
      body: 8.5,
      color: 7.0,
      briskness: 9.0,
      flavor: 6.5,
      finish: 6.0,
      overall: 7.0,
    },
    cupping_notes:
      "Strong, full-bodied CTC with excellent colour. Very brisk with good strength. Ideal for milk tea blends.",
    cupped_by: "Hassan Babikir (Port Sudan re-cupping)",
    cupping_date: "2026-03-18",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 200,
    min_purchase_kg: 10,
    reserve_price_per_kg: 2.0,
    starting_price_per_kg: 1.5,
    bid_increment: 0.1,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(10),
    auction_end: minutesFromNow(35),
    auto_extend_minutes: 3,
    status: "active",
    sample_available: false,
    ships_from_country: "KE",
    ships_from_city: "Mombasa",
    estimated_ship_days: 14,
    view_count: 45,
    bid_count: 3,
    watch_count: 5,
    created_at: daysAgo(1),
    updated_at: minutesAgo(15),
    seller: sellers[0],
    current_high_bid: 1.8,
  },
  {
    id: "lot7",
    seller_id: "s3",
    lot_number: "SB-2026-00148",
    title: "Ceylon OP1 - Dimbula Valley",
    description:
      "Classic Ceylon black tea from the Dimbula valley. Rich and full-flavored with bright coppery liquor.",
    origin_country: "LK",
    origin_region: "Dimbula",
    estate_name: "Somerset Estate",
    tea_type: "black",
    grade: "OP1",
    harvest_date: "2026-02-15",
    harvest_season: "first_flush",
    processing_method: "orthodox",
    elevation_meters: 1200,
    certifications: ["ETP (Ethical Tea Partnership)"],
    cupping: {
      aroma: 7.5,
      body: 8.0,
      color: 8.5,
      briskness: 7.5,
      flavor: 7.5,
      finish: 7.0,
      overall: 7.5,
    },
    cupping_notes:
      "Bright coppery-red liquor. Medium-bodied with notes of citrus and a clean, slightly malty finish.",
    cupped_by: "Priya Wickramasinghe",
    cupping_date: "2026-02-25",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 75,
    min_purchase_kg: 5,
    reserve_price_per_kg: 4.5,
    starting_price_per_kg: 3.0,
    buy_now_price_per_kg: 6.0,
    bid_increment: 0.1,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(35),
    auction_end: minutesFromNow(10),
    auto_extend_minutes: 3,
    status: "active",
    sample_available: true,
    sample_price: 3.0,
    ships_from_country: "LK",
    ships_from_city: "Colombo",
    estimated_ship_days: 9,
    view_count: 62,
    bid_count: 6,
    watch_count: 8,
    created_at: daysAgo(2),
    updated_at: minutesAgo(4),
    seller: sellers[2],
    current_high_bid: 4.2,
  },
  {
    id: "lot8",
    seller_id: "s4",
    lot_number: "SB-2026-00149",
    title: "Tie Guan Yin - Premium Oolong",
    description:
      "High-quality Tie Guan Yin from Anxi, Fujian. Light roast with complex floral and creamy notes.",
    origin_country: "CN",
    origin_region: "Anxi, Fujian",
    estate_name: "Anxi Tea Garden",
    tea_type: "oolong",
    grade: "GFOP",
    harvest_date: "2026-03-18",
    harvest_season: "first_flush",
    processing_method: "hand_rolled",
    elevation_meters: 800,
    certifications: [],
    cupping: {
      aroma: 9.5,
      body: 6.5,
      color: 8.0,
      briskness: 5.5,
      flavor: 9.0,
      finish: 9.0,
      overall: 8.5,
    },
    cupping_notes:
      "Intensely floral aroma — orchid and gardenia. Light golden-green liquor. Creamy, buttery mouthfeel with a long, sweet finish.",
    cupped_by: "Li Wei Chen",
    cupping_date: "2026-03-22",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 20,
    min_purchase_kg: 1,
    reserve_price_per_kg: 18.0,
    starting_price_per_kg: 12.0,
    buy_now_price_per_kg: 22.0,
    bid_increment: 0.5,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(20),
    auction_end: minutesFromNow(25),
    auto_extend_minutes: 3,
    status: "active",
    sample_available: true,
    sample_price: 6.0,
    ships_from_country: "CN",
    ships_from_city: "Xiamen",
    estimated_ship_days: 10,
    view_count: 93,
    bid_count: 8,
    watch_count: 19,
    created_at: daysAgo(2),
    updated_at: minutesAgo(6),
    seller: sellers[3],
    current_high_bid: 16.5,
  },
  // ============================================================
  // Sold lots — yesterday's and today's completed auctions
  // Used by the Market Feed and horizontal ticker on lot detail.
  // ============================================================
  {
    id: "sold1",
    seller_id: "s1",
    lot_number: "SB-2026-00135",
    title: "Kenya CTC PF1 - Feb 2026",
    description: "Strong brisk CTC from Kericho highlands.",
    origin_country: "KE",
    origin_region: "Kericho",
    estate_name: "Kipkelion Estate",
    tea_type: "black",
    grade: "CTC PF1",
    harvest_date: "2026-02-20",
    harvest_season: "rain",
    processing_method: "CTC",
    elevation_meters: 2100,
    certifications: ["Rainforest Alliance"],
    cupping: { aroma: 7.0, body: 8.0, color: 7.5, briskness: 8.5, flavor: 7.5, finish: 7.0, overall: 7.5 },
    cupping_notes: "Bright copper liquor, malty with clean finish.",
    cupped_by: "James Mwangi",
    cupping_date: "2026-02-25",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 200,
    min_purchase_kg: 50,
    reserve_price_per_kg: 3.8,
    starting_price_per_kg: 3.0,
    bid_increment: 0.1,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(120),
    auction_end: minutesAgo(75),
    auto_extend_minutes: 3,
    status: "sold",
    sample_available: false,
    ships_from_country: "KE",
    ships_from_city: "Mombasa",
    estimated_ship_days: 7,
    view_count: 134,
    bid_count: 22,
    watch_count: 38,
    created_at: daysAgo(3),
    updated_at: minutesAgo(75),
    seller: sellers[0],
    current_high_bid: 4.55,
    final_price_per_kg: 4.55,
    sold_at: minutesAgo(75),
    winning_buyer_id: "b1",
  },
  {
    id: "sold2",
    seller_id: "s3",
    lot_number: "SB-2026-00136",
    title: "Uganda BOP - March 2026",
    description: "Solid broken orange pekoe from western Uganda.",
    origin_country: "UG",
    origin_region: "Fort Portal",
    estate_name: "Rwenzori Tea Growers",
    tea_type: "black",
    grade: "BOP",
    harvest_date: "2026-03-05",
    harvest_season: "rain",
    processing_method: "CTC",
    elevation_meters: 1600,
    certifications: [],
    cupping: { aroma: 6.5, body: 7.0, color: 7.0, briskness: 7.5, flavor: 6.5, finish: 6.5, overall: 6.8 },
    cupping_notes: "Medium body, slightly astringent, good for blending.",
    cupped_by: "Grace Akello",
    cupping_date: "2026-03-08",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 500,
    min_purchase_kg: 100,
    reserve_price_per_kg: 2.5,
    starting_price_per_kg: 2.0,
    bid_increment: 0.05,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(90),
    auction_end: minutesAgo(45),
    auto_extend_minutes: 3,
    status: "sold",
    sample_available: false,
    ships_from_country: "UG",
    ships_from_city: "Kampala",
    estimated_ship_days: 10,
    view_count: 67,
    bid_count: 14,
    watch_count: 19,
    created_at: daysAgo(2),
    updated_at: minutesAgo(45),
    seller: sellers[2],
    current_high_bid: 2.95,
    final_price_per_kg: 2.95,
    sold_at: minutesAgo(45),
    winning_buyer_id: "b3",
  },
  {
    id: "sold3",
    seller_id: "s4",
    lot_number: "SB-2026-00137",
    title: "Rwanda OP1 - Feb 2026",
    description: "Hand-rolled orthodox from Nyungwe.",
    origin_country: "RW",
    origin_region: "Nyungwe",
    estate_name: "Nyungwe Tea Cooperative",
    tea_type: "black",
    grade: "OP1",
    harvest_date: "2026-02-28",
    harvest_season: "rain",
    processing_method: "orthodox",
    elevation_meters: 2400,
    certifications: ["UTZ Certified"],
    cupping: { aroma: 8.0, body: 8.5, color: 8.2, briskness: 8.0, flavor: 8.2, finish: 8.0, overall: 8.2 },
    cupping_notes: "Rich malty body, stone fruit, clean finish.",
    cupped_by: "Marie Uwase",
    cupping_date: "2026-03-02",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 8,
    min_purchase_kg: 1,
    reserve_price_per_kg: 28.0,
    starting_price_per_kg: 22.0,
    bid_increment: 0.5,
    currency: "USD",
    auction_duration_minutes: 30,
    auction_start: minutesAgo(180),
    auction_end: minutesAgo(150),
    auto_extend_minutes: 3,
    status: "sold",
    sample_available: false,
    ships_from_country: "RW",
    ships_from_city: "Kigali",
    estimated_ship_days: 7,
    view_count: 201,
    bid_count: 31,
    watch_count: 55,
    created_at: daysAgo(4),
    updated_at: minutesAgo(150),
    seller: sellers[3],
    current_high_bid: 31.20,
    final_price_per_kg: 31.20,
    sold_at: minutesAgo(150),
    winning_buyer_id: "b2",
  },
  {
    id: "sold4",
    seller_id: "s2",
    lot_number: "SB-2026-00138",
    title: "Darjeeling First Flush - Spring 2026",
    description: "Light, floral, muscatel character from Makaibari estate.",
    origin_country: "IN",
    origin_region: "Darjeeling",
    estate_name: "Makaibari Estate",
    tea_type: "black",
    grade: "FTGFOP1",
    harvest_date: "2026-03-20",
    harvest_season: "first_flush",
    processing_method: "orthodox",
    elevation_meters: 1500,
    certifications: ["Organic", "Fairtrade"],
    cupping: { aroma: 9.0, body: 6.5, color: 7.0, briskness: 7.0, flavor: 9.0, finish: 8.5, overall: 8.5 },
    cupping_notes: "Delicate muscatel with floral top notes, light amber liquor.",
    cupped_by: "Rajesh Gupta",
    cupping_date: "2026-03-22",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 3,
    min_purchase_kg: 1,
    reserve_price_per_kg: 18.0,
    starting_price_per_kg: 14.0,
    bid_increment: 0.5,
    currency: "USD",
    auction_duration_minutes: 30,
    auction_start: minutesAgo(240),
    auction_end: minutesAgo(210),
    auto_extend_minutes: 3,
    status: "sold",
    sample_available: false,
    ships_from_country: "IN",
    ships_from_city: "Kolkata",
    estimated_ship_days: 12,
    view_count: 156,
    bid_count: 19,
    watch_count: 44,
    created_at: daysAgo(5),
    updated_at: minutesAgo(210),
    seller: sellers[1],
    current_high_bid: 19.80,
    final_price_per_kg: 19.80,
    sold_at: minutesAgo(210),
    winning_buyer_id: "b4",
  },
  {
    id: "sold5",
    seller_id: "s1",
    lot_number: "SB-2026-00139",
    title: "Ceylon OP1 - March 2026",
    description: "Bright, full-bodied orthodox from Nuwara Eliya.",
    origin_country: "LK",
    origin_region: "Nuwara Eliya",
    estate_name: "Pedro Estate",
    tea_type: "black",
    grade: "OP1",
    harvest_date: "2026-03-12",
    harvest_season: "rain",
    processing_method: "orthodox",
    elevation_meters: 1900,
    certifications: ["Rainforest Alliance"],
    cupping: { aroma: 8.0, body: 7.5, color: 8.5, briskness: 8.0, flavor: 8.0, finish: 7.5, overall: 7.9 },
    cupping_notes: "Bright amber, citrus notes, brisk and clean.",
    cupped_by: "Anil Perera",
    cupping_date: "2026-03-14",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 25,
    min_purchase_kg: 5,
    reserve_price_per_kg: 7.0,
    starting_price_per_kg: 5.0,
    bid_increment: 0.2,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(60),
    auction_end: minutesAgo(15),
    auto_extend_minutes: 3,
    status: "sold",
    sample_available: false,
    ships_from_country: "LK",
    ships_from_city: "Colombo",
    estimated_ship_days: 10,
    view_count: 89,
    bid_count: 16,
    watch_count: 27,
    created_at: daysAgo(3),
    updated_at: minutesAgo(15),
    seller: sellers[0],
    current_high_bid: 8.40,
    final_price_per_kg: 8.40,
    sold_at: minutesAgo(15),
    winning_buyer_id: "b5",
  },
  {
    id: "sold6",
    seller_id: "s3",
    lot_number: "SB-2026-00140",
    title: "Kenya CTC BP1 - March 2026",
    description: "Bulk-grade broken pekoe, good for blending.",
    origin_country: "KE",
    origin_region: "Nandi Hills",
    estate_name: "Nandi Tea Factory",
    tea_type: "black",
    grade: "CTC BP1",
    harvest_date: "2026-03-08",
    harvest_season: "rain",
    processing_method: "CTC",
    elevation_meters: 2000,
    certifications: [],
    cupping: { aroma: 6.0, body: 7.5, color: 7.0, briskness: 8.0, flavor: 6.5, finish: 6.0, overall: 6.8 },
    cupping_notes: "Strong, full body, slightly dusty, blends well.",
    cupped_by: "James Mwangi",
    cupping_date: "2026-03-10",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 300,
    min_purchase_kg: 50,
    reserve_price_per_kg: 3.2,
    starting_price_per_kg: 2.5,
    bid_increment: 0.05,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: minutesAgo(360),
    auction_end: minutesAgo(315),
    auto_extend_minutes: 3,
    status: "sold",
    sample_available: false,
    ships_from_country: "KE",
    ships_from_city: "Mombasa",
    estimated_ship_days: 7,
    view_count: 45,
    bid_count: 9,
    watch_count: 11,
    created_at: daysAgo(4),
    updated_at: minutesAgo(315),
    seller: sellers[2],
    current_high_bid: 3.10,
    final_price_per_kg: 3.10,
    sold_at: minutesAgo(315),
    winning_buyer_id: "b1",
  },
  // -- ENDED / SOLD lots for dashboard testing --
  {
    id: "lot9",
    seller_id: "s1",
    lot_number: "SB-2026-00130",
    title: "Kericho BOP1 - February 2026",
    origin_country: "KE",
    origin_region: "Kericho",
    estate_name: "Kipkelion Estate",
    tea_type: "black",
    grade: "BOP1",
    processing_method: "CTC",
    certifications: ["Organic"],
    cupping: {
      aroma: 7.0,
      body: 7.5,
      color: 7.0,
      briskness: 8.0,
      flavor: 7.0,
      finish: 6.5,
      overall: 7.0,
    },
    cupping_notes: "Reliable, strong CTC. Good body.",
    cupped_by: "James Mwangi",
    cupping_date: "2026-02-10",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 100,
    min_purchase_kg: 10,
    reserve_price_per_kg: 2.5,
    starting_price_per_kg: 1.8,
    bid_increment: 0.1,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: daysAgo(5),
    auction_end: daysAgo(5),
    auto_extend_minutes: 3,
    status: "sold",
    ships_from_country: "KE",
    ships_from_city: "Mombasa",
    estimated_ship_days: 14,
    sample_available: false,
    view_count: 55,
    bid_count: 4,
    watch_count: 3,
    created_at: daysAgo(7),
    updated_at: daysAgo(5),
    seller: sellers[0],
    current_high_bid: 2.8,
  },
  {
    id: "lot10",
    seller_id: "s2",
    lot_number: "SB-2026-00131",
    title: "Assam TGFOP - Second Flush 2025",
    origin_country: "IN",
    origin_region: "Assam",
    estate_name: "Manohari Estate",
    tea_type: "black",
    grade: "TGFOP",
    processing_method: "orthodox",
    certifications: ["Fair Trade"],
    cupping: {
      aroma: 7.5,
      body: 9.0,
      color: 8.0,
      briskness: 8.5,
      flavor: 7.5,
      finish: 7.0,
      overall: 7.5,
    },
    cupping_notes: "Full-bodied Assam with malty character. Deep reddish liquor.",
    cupped_by: "Rajesh Sharma",
    cupping_date: "2025-10-15",
    photo_dry_leaf: "/placeholder-tea-dry.jpg",
    photo_wet_leaf: "/placeholder-tea-wet.jpg",
    photo_liquor: "/placeholder-tea-liquor.jpg",
    photo_packaging: "/placeholder-tea-pack.jpg",
    photos_additional: [],
    total_kg: 40,
    min_purchase_kg: 5,
    reserve_price_per_kg: 6.0,
    starting_price_per_kg: 4.0,
    bid_increment: 0.5,
    currency: "USD",
    auction_duration_minutes: 45,
    auction_start: daysAgo(3),
    auction_end: daysAgo(3),
    auto_extend_minutes: 3,
    status: "counter_offer",
    counter_offer_price_per_kg: 5.5,
    counter_offer_expires_at: minutesFromNow(20),
    counter_offer_buyer_id: "b1",
    ships_from_country: "IN",
    ships_from_city: "Kolkata",
    estimated_ship_days: 12,
    sample_available: true,
    sample_price: 4.0,
    view_count: 78,
    bid_count: 6,
    watch_count: 9,
    created_at: daysAgo(5),
    updated_at: daysAgo(3),
    seller: sellers[1],
    current_high_bid: 5.0,
  },
];

// ============================================================
// BIDS
// ============================================================
export const bids: Bid[] = [
  // Lot 1 bids
  {
    id: "bid1",
    lot_id: "lot1",
    buyer_id: "b1",
    amount_per_kg: 3.5,
    kg_requested: 50,
    is_winning: false,
    status: "outbid",
    bid_source: "manual",
    placed_at: minutesAgo(20),
  },
  {
    id: "bid2",
    lot_id: "lot1",
    buyer_id: "b2",
    amount_per_kg: 3.8,
    kg_requested: 50,
    is_winning: false,
    status: "outbid",
    bid_source: "manual",
    placed_at: minutesAgo(18),
  },
  {
    id: "bid3",
    lot_id: "lot1",
    buyer_id: "b1",
    amount_per_kg: 4.0,
    kg_requested: 50,
    is_winning: false,
    status: "outbid",
    bid_source: "manual",
    placed_at: minutesAgo(15),
  },
  {
    id: "bid4",
    lot_id: "lot1",
    buyer_id: "b3",
    amount_per_kg: 4.3,
    kg_requested: 50,
    is_winning: false,
    status: "outbid",
    bid_source: "manual",
    placed_at: minutesAgo(10),
  },
  {
    id: "bid5",
    lot_id: "lot1",
    buyer_id: "b2",
    amount_per_kg: 4.5,
    kg_requested: 50,
    is_winning: false,
    status: "outbid",
    bid_source: "manual",
    placed_at: minutesAgo(7),
  },
  {
    id: "bid6",
    lot_id: "lot1",
    buyer_id: "b1",
    amount_per_kg: 4.6,
    kg_requested: 50,
    is_winning: false,
    status: "outbid",
    bid_source: "manual",
    placed_at: minutesAgo(5),
  },
  {
    id: "bid7",
    lot_id: "lot1",
    buyer_id: "b3",
    amount_per_kg: 4.8,
    kg_requested: 50,
    is_winning: true,
    status: "active",
    bid_source: "manual",
    placed_at: minutesAgo(3),
  },
  // Lot 2 bids
  {
    id: "bid8",
    lot_id: "lot2",
    buyer_id: "b1",
    amount_per_kg: 8.0,
    kg_requested: 25,
    is_winning: false,
    status: "outbid",
    bid_source: "manual",
    placed_at: minutesAgo(25),
  },
  {
    id: "bid9",
    lot_id: "lot2",
    buyer_id: "b4",
    amount_per_kg: 9.5,
    kg_requested: 25,
    is_winning: false,
    status: "outbid",
    bid_source: "manual",
    placed_at: minutesAgo(20),
  },
  {
    id: "bid10",
    lot_id: "lot2",
    buyer_id: "b1",
    amount_per_kg: 10.5,
    kg_requested: 25,
    is_winning: false,
    status: "outbid",
    bid_source: "manual",
    placed_at: minutesAgo(12),
  },
  {
    id: "bid11",
    lot_id: "lot2",
    buyer_id: "b4",
    amount_per_kg: 11.5,
    kg_requested: 25,
    max_auto_bid: 14.0,
    is_winning: true,
    status: "active",
    bid_source: "manual",
    placed_at: minutesAgo(8),
  },
];

// ============================================================
// ORDERS
// ============================================================
export const orders: Order[] = [
  {
    id: "ord1",
    order_number: "ORD-2026-00089",
    lot_id: "lot9",
    bid_id: "bid-old-1",
    buyer_id: "b1",
    seller_id: "s1",
    order_type: "auction_win",
    price_per_kg: 2.8,
    total_kg: 100,
    subtotal: 280,
    buyer_premium_pct: 7.5,
    buyer_premium_amount: 21,
    shipping_cost: 45,
    total_amount: 346,
    seller_payout: 272.2,
    payment_status: "released",
    paid_at: daysAgo(5),
    fulfillment_status: "delivered",
    tracking_number: "KE1234567890",
    tracking_carrier: "DHL",
    shipped_at: daysAgo(4),
    delivered_at: daysAgo(1),
    buyer_confirmed_at: daysAgo(1),
    quality_matches_report: true,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
    lot: lots[8],
    seller: sellers[0],
  },
];

// ============================================================
// COUNTER-OFFERS
// ============================================================
export const counterOffers: CounterOffer[] = [
  {
    id: "co1",
    lot_id: "lot10",
    seller_id: "s2",
    buyer_id: "b1",
    original_bid_id: "bid-old-2",
    highest_bid_amount: 5.0,
    seller_counter_price: 5.5,
    status: "sent",
    expires_at: minutesFromNow(20),
    created_at: minutesAgo(10),
    lot: lots[9],
    seller: sellers[1],
  },
];

// ============================================================
// NOTIFICATIONS
// ============================================================
export const notifications: Notification[] = [
  {
    id: "n1",
    user_id: "b1",
    type: "outbid",
    title: "You've been outbid!",
    body: "Someone bid $4.80/kg on Kericho Gold GFBOP. 23 min left.",
    lot_id: "lot1",
    action_url: "/auctions/lot1",
    read: false,
    push_sent: true,
    created_at: minutesAgo(3),
  },
  {
    id: "n2",
    user_id: "b1",
    type: "counter_offer_received",
    title: "Counter-offer received",
    body: "Darjeeling First Flush countered at $5.50/kg (you bid $5.00/kg). 20 min to respond.",
    lot_id: "lot10",
    counter_offer_id: "co1",
    action_url: "/dashboard/buyer/counter-offers",
    read: false,
    push_sent: true,
    created_at: minutesAgo(10),
  },
  {
    id: "n3",
    user_id: "b1",
    type: "auction_won",
    title: "You won!",
    body: "You won Kericho BOP1 at $2.80/kg. Complete payment now.",
    lot_id: "lot9",
    order_id: "ord1",
    action_url: "/dashboard/buyer/orders",
    read: true,
    push_sent: true,
    created_at: daysAgo(5),
  },
];

// ============================================================
// REVIEWS
// ============================================================
export const reviews: SellerReview[] = [
  {
    id: "rev1",
    order_id: "ord1",
    buyer_id: "b1",
    seller_id: "s1",
    tcr_accuracy: 5,
    packaging_quality: 4,
    shipping_speed: 4,
    overall: 5,
    comment:
      "Tea matched the condition report perfectly. Excellent packaging, well-sealed bags.",
    created_at: daysAgo(1),
  },
];

// ============================================================
// Mock auth context — switch between roles for testing
// ============================================================
export type MockUser = Profile & { role: "buyer" | "seller" | "admin" };

export const mockUsers: Record<string, MockUser> = {
  buyer: { ...buyers[0], role: "buyer" },
  seller: { ...sellers[0], role: "seller" },
  admin: { ...adminUser, role: "admin" },
};

// ============================================================
// Live-timestamp refresh for active lots
// ----------------------------------------------------------------
// The `lots` array above captures timestamps at MODULE LOAD time.
// That's wrong for a long-running demo: by the time the investor
// opens the tunnel URL, the server might have been running for
// an hour and every auction would show ENDED.
//
// Fix: store each active lot's auction window as offsets from "now"
// and recompute the ISO strings on every `getActiveLots()` /
// `getLotById()` call. This way the countdown is always live.
// ============================================================
const ACTIVE_LOT_TIMING: Record<
  string,
  { startOffsetMin: number; durationMin: number }
> = {
  lot1: { startOffsetMin: -22, durationMin: 45 },
  lot2: { startOffsetMin: -30, durationMin: 45 },
  lot3: { startOffsetMin: -15, durationMin: 60 },
  lot4: { startOffsetMin: -40, durationMin: 45 },
  // lot5 is the demo lot — 20-second main auction that starts on page
  // load. Short enough to fit the full flow inside a 60s YouTube Short
  // (main round + closing round + SOLD stamp).
  lot5: { startOffsetMin: 0, durationMin: 0.33 },
  lot6: { startOffsetMin: -10, durationMin: 45 },
  lot7: { startOffsetMin: -35, durationMin: 45 },
  lot8: { startOffsetMin: -20, durationMin: 45 },
};

function refreshLotTimestamps(lot: Lot): Lot {
  const timing = ACTIVE_LOT_TIMING[lot.id];
  if (!timing) return lot;
  const now = Date.now();
  const start = new Date(now + timing.startOffsetMin * 60 * 1000);
  const end = new Date(start.getTime() + timing.durationMin * 60 * 1000);
  return {
    ...lot,
    auction_start: start.toISOString(),
    auction_end: end.toISOString(),
  };
}

// ============================================================
// HELPERS for looking up data
// ============================================================
export function getLotById(id: string): Lot | undefined {
  const lot = lots.find((l) => l.id === id);
  return lot ? refreshLotTimestamps(lot) : undefined;
}

export function getBidsForLot(lotId: string): Bid[] {
  return bids
    .filter((b) => b.lot_id === lotId)
    .sort(
      (a, b) =>
        new Date(b.placed_at).getTime() - new Date(a.placed_at).getTime()
    );
}

export function getActiveLots(): Lot[] {
  return lots.filter((l) => l.status === "active").map(refreshLotTimestamps);
}

export function getProfileById(id: string): Profile | undefined {
  return allProfiles.find((p) => p.id === id);
}

export function getSoldLots(): Lot[] {
  return lots
    .filter((l) => l.status === "sold")
    .sort(
      (a, b) =>
        new Date(b.sold_at!).getTime() - new Date(a.sold_at!).getTime()
    );
}

export function getMarketTickerItems(): TickerItem[] {
  const active = getActiveLots().map((l) => {
    const current = l.current_high_bid || l.starting_price_per_kg;
    const change = +(current - l.starting_price_per_kg).toFixed(2);
    const parts = `${getCountryFlag(l.origin_country)} ${l.grade}`.trim();
    return {
      symbol: parts,
      price: current,
      change: Math.abs(change),
      direction: (change >= 0 ? "up" : "down") as "up" | "down",
    };
  });

  const sold = getSoldLots().map((l) => {
    const final_ = l.final_price_per_kg!;
    const change = +(final_ - l.reserve_price_per_kg).toFixed(2);
    const parts = `${getCountryFlag(l.origin_country)} ${l.grade}`.trim();
    return {
      symbol: parts,
      price: final_,
      change: Math.abs(change),
      direction: (change >= 0 ? "up" : "down") as "up" | "down",
    };
  });

  return [...active, ...sold];
}
